name: custom_scaffold_plus
description: "A powerful, flexible, and production-ready alternative to Flutter's native Scaffold with features like scrollable content, background images, and more."
version: 1.0.3
homepage: https://github.com/berhili098/custom_scaffold_plus
repository: https://github.com/berhili098/custom_scaffold_plus
issue_tracker: https://github.com/berhili098/custom_scaffold_plus/issues
documentation: https://github.com/berhili098/custom_scaffold_plus#readme

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  # Add assets if needed
  assets:
  - assets/
